# Generated by Django 3.2.4 on 2021-06-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmpy_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crousel',
        ),
    ]
