# Generated by Django 3.2.4 on 2021-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmpy_profile', '0002_delete_crousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobdev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_name', models.CharField(max_length=50)),
                ('mob_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='mobiledevelopment/images')),
            ],
        ),
        migrations.CreateModel(
            name='Webdev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=50)),
                ('web_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='webdevelopment/images')),
            ],
        ),
    ]
