# Generated by Django 3.2.4 on 2021-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpy_profile', '0003_mobdev_webdev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(max_length=50)),
                ('cloud_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='cloud/images')),
            ],
        ),
        migrations.CreateModel(
            name='UI_UX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ui_name', models.CharField(max_length=50)),
                ('Ui_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='Ui/images')),
            ],
        ),
    ]
