# Generated by Django 3.2.4 on 2021-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpy_profile', '0004_cloud_ui_ux'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_name', models.CharField(max_length=50)),
                ('cms_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='cms/images')),
            ],
        ),
        migrations.CreateModel(
            name='HDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdr_name', models.CharField(max_length=50)),
                ('hdr_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='hdr/images')),
            ],
        ),
        migrations.CreateModel(
            name='Video_editing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50)),
                ('video_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='video/images')),
            ],
        ),
        migrations.RenameField(
            model_name='ui_ux',
            old_name='Ui_description',
            new_name='ui_description',
        ),
        migrations.RenameField(
            model_name='ui_ux',
            old_name='Ui_name',
            new_name='ui_name',
        ),
    ]
