# Generated by Django 3.2.4 on 2021-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpy_profile', '0005_auto_20210614_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=50)),
                ('cont_email', models.EmailField(default='', max_length=254)),
                ('cont_desc', models.CharField(default='', max_length=450)),
                ('cont_file', models.FileField(upload_to='')),
            ],
        ),
    ]
